name: Deploy Staffly Management Application to Production Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Composer Dependencies
      run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

 
    
    - name: Synchronize Files To Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.VPS_HOST }}
        REMOTE_USER: ${{ secrets.VPS_USER }}
        TARGET: "/var/www/html/employee-management-system"

    - name: Run Remote/Artisan Commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/html/employee-management-system
          sudo chown -R www-data:www-data .
          sudo chmod -R 775 storage bootstrap/cache
          composer install --optimize-autoloader --no-dev --no-interaction

          php artisan migrate --force
          php artisan optimize:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan optimize
    - name: Install NPM Dependencies
      run: npm ci # Add this step to install dependencies

    - name: Build Assets
      run: npm run build # Run the build process after dependencies are installed







